baseURL = "https://resistentialist.com/"
languageCode = "en-us"
title = "Resistentialist"
theme = "minimal"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[params]
    author = "Charles Allhands"
    # profilePic = ""
    description = "Charles Allhands. Welcome to my site."
    githubUsername = "callhands"
    accent = "green"
    showBorder = true
    backgroundColor = "#fffff8"
    font = "Open Sans" # Raleway should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "python", "swift"]
    rssLimit = 20

[author]
    name = "Charles Allhands"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:charles.allhands@wisc.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/callhands"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "/post/index.xml"
    name = "rss"
    weight = 3
